# -*- coding: utf-8 -*-
"""Common Operation on Binary Heap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ieUbn8f2cor8eiqd-ZF358m_Oo3wehXC
"""

# creation of Binary Heap
class Heap:
    def __init__(self,size):
        self.customList = (size+1) * [None]
        self.heapSize = 0
        self.maxSize = size + 1

# peek of binary heap
def peekofHeap(rootNode):
    if not rootNode:
        return
    else:
        return rootNode.customList[1]

# size of Heap
def sizeofHeap(rootNode):
    if not rootNode:
        return
    else:
        return rootNode.heapSize

# traversal in binary heap
def levelOrderTraversal(rootNode):
    if not rootNode:
        return
    else:
        for i in range(1,rootNode.heapSize+1):
            print(rootNode.customList[i])

newBinaryHeap = Heap(5)
print(sizeofHeap(newBinaryHeap))