# -*- coding: utf-8 -*-
"""Create a BST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k0yj_qPSVF0WaSjW0THFF2dt9Ds7y_pO
"""

class BSTNode:
    def __init__(self,data):
        self.data = data
        self.leftChild = None
        self.rightChild = None

newBST = BSTNode(None)

# Time Complexity - 0(1)
# Space Complexity - 0(1)