# -*- coding: utf-8 -*-
"""Create Binary Tree Using Python List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3AxP5v3GsOGMRVuDqzYNxopcHy3BuPj
"""

class BinaryTree:
    def __init__(self,size):
        self.customList = size * [None]
        self.lastUsedIndex = 0
        self.maxSize = size

newBT = BinaryTree(8)

# Time Complexity - 0(1)
# Space Complexity - 0(n)