# -*- coding: utf-8 -*-
"""Create Binary Tree Using LinkedList.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ISAon3AoFLBXJBJmIQvb1zHGy0xyyWz
"""

class TreeNode:
    def __init__(self,data):
        self.data = data
        self.leftchild = None
        self.rightchild = None

    
newBT = TreeNode("Drinks")

#timecomplexity = 0(1)
#spacecomplexity = 0(1)